openapi: 3.0.0
info:
  title: SSO API Documentation
  version: 1.0.0
  description: API centralizada de Single Sign-On y Gestión de Identidades (IAM).

paths:
  # --- OAUTH ---
  /oauth/token:
    $ref: './paths/oauth.yaml#/Token'
  /oauth/authorize:
    $ref: './paths/oauth.yaml#/Authorize'
  /oauth/revok:
    $ref: './paths/oauth.yaml#/Revoke'

  # --- CLIENTS ---
  '/api/v1/client/{id}':
    $ref: './paths/client.yaml#/ClientItem'
  /api/v1/client:
    $ref: './paths/client.yaml#/CreateClient'
  /api/v1/clients:
    $ref: './paths/client.yaml#/GetClients'
  '/api/v1/grants/{id}':
    $ref: './paths/Grants.yaml#/AssignGrants'
  '/api/v1/client/grants':
    $ref: './paths/client.yaml#/GetGrantsList'
  '/api/v1/client/file/{id}':
    $ref: './paths/client.yaml#/PutImage'

  # --- COMPANY / UNITS ---
  '/api/v1/company/{id}':
    $ref: './paths/units.yaml#/CompanyItem'
  /api/v1/company:
    $ref: './paths/units.yaml#/PostCompany'
  /api/v1/companys:
    $ref: './paths/units.yaml#/GeUnits'
  '/api/v1/company/branch/{location}/{branch}':
    $ref: './paths/units.yaml#/PutBranch'
  '/api/v1/company/branch/{branch}':
    $ref: './paths/units.yaml#/DeleteBranch'
  '/api/v1/company/{unit}':
    $ref: './paths/units.yaml#/DeleteUnit'
  '/api/v1/company/branch/{unit}':
    $ref: './paths/units.yaml#/PostBranch'
  '/api/v1/company/file/{id}':
    $ref: './paths/units.yaml#/PutImage'

  # --- ROLES ---
  /api/v1/rols:
    $ref: './paths/Rol.yaml#/GetRoles'
  '/api/v1/rol/{id}':
    $ref: './paths/Rol.yaml#/GetRoleById'
  '/api/v1/rols/{id}':
    $ref: './paths/Rol.yaml#/PostRoleAssignment'
  /api/v1/rol:
    $ref: './paths/Rol.yaml#/PostRole'

  # --- USERS ---
  /api/v1/users:
    $ref: './paths/users.yaml#/GetUsers'
  /api/v1/user:
    $ref: './paths/users.yaml#/PostUser'
  '/api/v1/user/{id}':
    $ref: './paths/users.yaml#/UserItem'
  '/api/v1/user/image/{id}':
    $ref: './paths/users.yaml#/PostUserImage'
  '/api/v1/user/password/{id}':
    $ref: './paths/users.yaml#/PostResetPassword'
  '/api/v1/user/preferences/{id}':
    $ref: './paths/users.yaml#/PutUserPreferences'
  '/api/v1/user/details/{id}':
    $ref: './paths/users.yaml#/GetUserDetail'
  '/api/v1/user/revoke/{id}':
    $ref: './paths/users.yaml#/RevokeSession'
  /api/v1/user/federate:
    $ref: './paths/users.yaml#/GetFederateData'
  /api/v1/user/download:
    $ref: './paths/users.yaml#/DownloadImage'

components:
  schemas:
    ClientResponse:
      $ref: './schemas/ClientResponse.yaml#/ClientSchema'
    Grant:
      $ref: './schemas/Grant.yaml'
    CreateClientRequest:
      $ref: './schemas/ClientResponse.yaml#/ClientReq'
    Units:
      $ref: './schemas/Unit.yaml'

  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: '/oauth/authorize'
          tokenUrl: '/oauth/token'
        password:
          tokenUrl: '/oauth/token'
        clientCredentials:
          tokenUrl: '/oauth/token'
