GetClient:
  summary: Obtiene un client APP por identificador
  tags:
    - Client
  security:
    - OAuth2: []
  parameters:
    - in: path
      name: id
      required: true
      schema:
        type: string
      description: ID del usuario
  responses:
    '200':
      description: Lista de clients
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 200
              statusCode:
                type: integer
                example: 200
              data:
                $ref: '../schemas/ClientResponse.yaml#/ClientSchema'
CreateClient:
  post:
    summary: Crear cliente con archivo adjunto
    tags:
      - Client
    security:
      - OAuth2: []
    requestBody:
      content:
        multipart/form-data:
          schema:
            $ref: '../schemas/ClientResponse.yaml#/ClientReq'
    responses:
      '200':
        description: Cliente creado exitosamente
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: integer
                  example: 200
                statusCode:
                  type: integer
                  example: 200
                data:
                  $ref: '../schemas/ClientResponse.yaml#/ClientSchema'
GetClients:
  get:
    summary: Obtiene una lista de clients paginados por 20 filas
    tags:
      - Client
    security:
      - OAuth2: []
    parameters:
      - in: query
        name: page
        required: false
        schema:
          type: integer
        description: Página actual
      - in: query
        name: pageSize
        required: false
        schema:
          type: integer
        description: Cantidad total por consulta
      - in: query
        name: q
        required: false
        schema:
          type: string
        description: Filtros custom
    responses:
      '200':
        description: Lista de clients
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: integer
                  example: 200
                statusCode:
                  type: integer
                  example: 200
                data:
                  type: array
                  items:
                    $ref: '../schemas/ClientResponse.yaml#/ClientSchema'
                page:
                  type: integer
                  example: 2
                pageSize:
                  type: integer
                  example: 20
                totalCount:
                  type: integer
                  example: 200
DeleteClient:
  summary: Elimina un cliente por ID
  tags:
    - Client
  security:
    - OAuth2: []
  parameters:
    - in: path
      name: id
      required: true
      schema:
        type: string
      description: ID del cliente a eliminar
  responses:
    '201':
      description: Cliente eliminado exitosamente
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 201
              statusCode:
                type: integer
                example: 201
              data:
                type: string
                nullable: true
                example: null
UpdateClient:
  summary: Actualiza un cliente por ID
  tags:
    - Client
  security:
    - OAuth2: []
  parameters:
    - in: path
      name: id
      required: true
      schema:
        type: string
      description: ID del cliente a actualizar
    - in: query
      name: pub
      required: false
      schema:
        type: string
      description: Identificador público para la imagen (public_id)
  requestBody:
    required: true
    content:
      multipart/form-data:
        schema:
          type: object
          properties:
            file:
              type: string
              format: binary
              description: Imagen del cliente
            payload:
              type: string
              description: JSON serializado como string con los datos del cliente
  responses:
    '201':
      description: Cliente actualizado exitosamente
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 201
              statusCode:
                type: integer
                example: 201
              data:
                $ref: '../schemas/ClientResponse.yaml#/ClientSchema'
GetGrantsList:
  get:
    summary: Lista todos los grants disponibles
    tags:
      - Client
    security:
      - OAuth2: []
    responses:
      '200':
        description: Lista de grants
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: integer
                  example: 200
                statusCode:
                  type: integer
                  example: 200
                data:
                  type: array
                  items:
                    $ref: '../schemas/Grant.yaml'

