ClientItem:
  get:
    summary: Obtiene un client APP por identificador
    tags:
      - Client
    security:
      - OAuth2: []
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    responses:
      '200':
        description: Cliente obtenido
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: integer
                statusCode:
                  type: integer
                data:
                  $ref: '../schemas/ClientResponse.yaml#/ClientSchema'
  put:
    summary: Actualiza un cliente por ID
    tags:
      - Client
    security:
      - OAuth2: []
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '../schemas/ClientResponse.yaml#/ClientReq'
    responses:
      '201':
        description: Cliente actualizado
  delete:
    summary: Elimina un cliente por ID
    tags:
      - Client
    security:
      - OAuth2: []
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    responses:
      '201':
        description: Cliente eliminado

CreateClient:
  post:
    summary: Crear cliente
    tags:
      - Client
    security:
      - OAuth2: []
    requestBody:
      content:
        application/json:
          schema:
            $ref: '../schemas/ClientResponse.yaml#/ClientReq'
    responses:
      '201':
        description: Cliente creado

GetClients:
  get:
    summary: Obtiene una lista de clients
    tags:
      - Client
    security:
      - OAuth2: []
    parameters:
      - in: query
        name: page
        schema:
          type: integer
    responses:
      '200':
        description: Lista de clientes

GetGrantsList:
  get:
    summary: Lista todos los grants disponibles
    tags:
      - Client
    security:
      - OAuth2: []
    responses:
      '200':
        description: Lista de grants

PutImage:
  put:
    summary: Cargar o actualizar icono de aplicacion
    tags:
      - Client
    security:
      - OAuth2: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    requestBody:
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              file:
                type: string
                format: binary
    responses:
      '200':
        description: Imagen cargada
