GetRoles:
  get:
    summary: Obtener lista de roles
    tags:
      - Roles
    security:
      - OAuth2: []
    parameters:
      - name: page
        in: query
        schema:
          type: integer
    responses:
      '200':
        description: Lista de roles

GetRoleById:
  get:
    summary: Obtener un rol por su identificador
    tags:
      - Roles
    security:
      - OAuth2: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    responses:
      '200':
        description: Rol obtenido

PostRoleAssignment:
  post:
    summary: Asignar o revocar roles a un usuario
    tags:
      - Roles
    security:
      - OAuth2: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '../schemas/RequestRols.yaml#/RequestGrantRol'
    responses:
      '201':
        description: Roles gestionados exitosamente

PostRole:
  post:
    summary: Crear un nuevo rol
    tags:
      - Roles
    security:
      - OAuth2: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              rol:
                type: object
                properties:
                  rol_name:
                    type: string
                  rol_code:
                    type: string
    responses:
      '201':
        description: Rol creado
