CompanyItem:
  get:
    summary: Obtiene una empresa por ID
    tags:
      - Company
    security:
      - OAuth2: []
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    responses:
      '200':
        description: Empresa encontrada
  put:
    summary: Actualizar una unidad de negocio
    tags:
      - Company
    security:
      - OAuth2: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '../schemas/RequestBu.yaml#/BusinessUnitInput'
    responses:
      '201':
        description: Empresa actualizada

PostCompany:
  post:
    summary: Crear una nueva unidad de negocio
    tags:
      - Company
    security:
      - OAuth2: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              bu:
                $ref: '../schemas/RequestBu.yaml#/BusinessUnitInput'
    responses:
      '201':
        description: Empresa creada

GeUnits:
  get:
    summary: Obtener todas las unidades
    tags:
      - Company
    security:
      - OAuth2: []
    responses:
      '200':
        description: Lista de unidades

PutBranch:
  put:
    summary: Actualizar sucursal
    tags:
      - Company
    security:
      - OAuth2: []
    parameters:
      - name: location
        in: path
        required: true
        schema:
          type: string
      - name: branch
        in: path
        required: true
        schema:
          type: string
    responses:
      '201':
        description: Sucursal actualizada

DeleteBranch:
  delete:
    summary: Eliminar sucursal
    tags:
      - Company
    security:
      - OAuth2: []
    parameters:
      - name: branch
        in: path
        required: true
        schema:
          type: string
    responses:
      '201':
        description: Sucursal eliminada

DeleteUnit:
  delete:
    summary: Eliminar unidad
    tags:
      - Company
    security:
      - OAuth2: []
    parameters:
      - name: unit
        in: path
        required: true
        schema:
          type: string
    responses:
      '201':
        description: Unidad eliminada

PostBranch:
  post:
    summary: Crear sucursal
    tags:
      - Company
    security:
      - OAuth2: []
    parameters:
      - name: unit
        in: path
        required: true
        schema:
          type: string
    responses:
      '201':
        description: Sucursal creada

PutImage:
  put:
    summary: Cargar imagen de empresa
    tags:
      - Company
    security:
      - OAuth2: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    responses:
      '200':
        description: Imagen cargada
