--CREATE UNIQUE INDEX IDX_SSO_USERS_EMAIL ON "public"."SSO_AUTH_USERS_T"(EMAIL);
--CREATE UNIQUE INDEX IDX_SSO_USERS_ID    ON "public"."SSO_AUTH_USERS_T"(ID);
CREATE INDEX IDX_SSO_USERS_LAST_LOGIN ON "public"."SSO_AUTH_USERS_T"(LAST_LOGIN);


CREATE INDEX  IDX_SSO_USERS_INFO ON "public"."SSO_AUTH_EMPLOYEE_INFO_T"(USER_ID);



--CREATE INDEX IDX_SSO_ROLES_ID  ON "public"."SSO_AUTH_ROLES_T"(ID);
CREATE UNIQUE INDEX IDX_SSO_ROLES_RLC ON "public"."SSO_AUTH_ROLES_T"(ROL_CODE);

CREATE INDEX IDX_SSO_AUTH_ACCESS ON "public"."SSO_AUTH_ACCESS_L"(USER_ID,ROLE_ID);

CREATE UNIQUE INDEX IDX_SSO_AUTH_TOKEN   ON "public"."SSO_AUTH_TOKEN_T"(ACCESS_TOKEN);
CREATE UNIQUE INDEX IDX_SSO_AUTH_REFRESH ON "public"."SSO_AUTH_TOKEN_T"(REFRESH_TOKEN);
CREATE  INDEX IDX_SSO_AUTH_CLIEN ON "public"."SSO_AUTH_TOKEN_T"(CLIENT_ID);
CREATE  INDEX IDX_SSO_AUTH_USER  ON "public"."SSO_AUTH_TOKEN_T"(USER_ID);

CREATE UNIQUE INDEX IDX_SSO_CLIENT_NAME ON "public"."SSO_AUTH_CLIENTS_T"(APP_NAME);
CREATE INDEX IDX_SSO_CLIENT_ID ON "public"."SSO_AUTH_CLIENTS_T"(CLIENT_ID,CLIENT_SECRET);

CREATE INDEX IDX_SSO_GRANTS_CL ON "public"."SSO_AUTH_GRANTS_T"(CLIENT_ID);
CREATE INDEX IDX_SSO_GRANTS_NM ON "public"."SSO_AUTH_GRANTS_T"(GRANT_NAME);
