CREATE EXTENSION pgcrypto;

CREATE TABLE "public"."SSO_AUTH_USERS_T" (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USERNAME VARCHAR(50) NOT NULL,--
    NAME VARCHAR(100) NOT NULL,--
    LAST_NAME VARCHAR(100) NOT NULL,--
    EMAIL VARCHAR(150) UNIQUE NOT NULL,--
    PHONE VARCHAR(20),
    PASSWORD TEXT NOT NULL,
    PROFILE_PICTURE TEXT,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    LAST_LOGIN TIMESTAMP,
    RESET_TOKEN TEXT,
    VERIFIED BOOLEAN DEFAULT FALSE,
    BIO TEXT,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE "public"."SSO_AUTH_EMPLOYEE_INFO_T" (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USER_ID UUID NOT NULL,
    JOB_TITLE VARCHAR(100),
    DEPARTMENT VARCHAR(50),
    COMPANY_NAME VARCHAR(100),
    LOCATION VARCHAR(100),
    HIRE_DATE TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (USER_ID) REFERENCES "public"."SSO_AUTH_USERS_T"(ID) ON DELETE CASCADE
);

CREATE TABLE "public"."SSO_AUTH_ROLES_T" (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ROL_NAME VARCHAR(50) UNIQUE NOT NULL,
    ROL_CODE VARCHAR(50) UNIQUE NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATE_BY VARCHAR(50) NOT NULL,
    LAST_UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "public"."SSO_AUTH_ACCESS_L" (
    USER_ID UUID NOT NULL,
    ROLE_ID UUID NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATE_BY VARCHAR(50) NOT NULL,
    LAST_UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_sso_auth_access PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT fk_user FOREIGN KEY (USER_ID) REFERENCES "public"."SSO_AUTH_USERS_T"(ID) ON DELETE CASCADE,
    CONSTRAINT fk_role FOREIGN KEY (ROLE_ID) REFERENCES "public"."SSO_AUTH_ROLES_T"(ID) ON DELETE CASCADE
);

CREATE TABLE "public"."SSO_AUTH_CLIENTS_T" (
    APP_NAME VARCHAR(200) NOT NULL,
    CLIENT_ID VARCHAR(100) PRIMARY KEY DEFAULT encode(gen_random_bytes(32), 'hex'),
    CLIENT_SECRET VARCHAR(100) DEFAULT encode(gen_random_bytes(16), 'hex'),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "public"."SSO_AUTH_TOKEN_T"(
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USER_ID UUID NULL,
    CLIENT_ID VARCHAR(100) NULL,
    ACCESS_TOKEN VARCHAR(600) NOT NULL,
    REFRESH_TOKEN VARCHAR(600) NOT NULL,
    ACCESS_EXPIRES TIMESTAMP,
    ACCESS_REFRESH TIMESTAMP,
    CONSTRAINT fk_usr FOREIGN KEY (USER_ID) REFERENCES "public"."SSO_AUTH_USERS_T"(ID),
    CONSTRAINT fk_client FOREIGN KEY (CLIENT_ID) REFERENCES "public"."SSO_AUTH_CLIENTS_T"(CLIENT_ID)
);

CREATE TABLE "public"."SSO_AUTH_GRANTS_T" (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CLIENT_ID VARCHAR(100) NOT NULL,
    GRANT_NAME VARCHAR(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_grants FOREIGN KEY (CLIENT_ID) REFERENCES "public"."SSO_AUTH_CLIENTS_T"(CLIENT_ID)
);



