ClientSchema:
  type: object
  properties:
    client_secret:
      type: string
      nullable: true
      example: "abc123secret"
    client_id:
      type: string
      example: "client-001"
    app_name:
      type: string
      nullable: true
      example: "Mi App"
    description:
      type: string
      nullable: true
      example: "Aplicación de ejemplo"
    redirect_callback:
      type: string
      nullable: true
      example: "https://miapp.com/callback"
    scopes:
      type: string
      nullable: true
      example: "read write"
    is_active:
      type: boolean
      nullable: true
      example: true
    app_type:
      type: string
      nullable: true
      example: "public"
    client_icon_url:
      type: string
      nullable: true
      example: "https://miapp.com/icon.png"
    created_by:
      type: string
      nullable: true
      example: "admin"
    grants:
      type: array
      items:
        $ref: './Grant.yaml'

ClientReq:
  type: object
  properties:
    app:
      type: string
      description: Nombre de la aplicación cliente
    grants:
      type: array
      items:
        type: string
      description: Lista de permisos otorgados (grants)
    data:
      type: object
      properties:
        description:
          type: string
          description: Descripción de la aplicación
        redirect_callback:
          type: string
          format: uri
          description: URL de redirección para el callback
        scopes:
          type: string
          description: Alcances autorizados para el cliente
        app_type:
          type: string
          description: Tipo de aplicación (ej. web, móvil, servicio)
      required:
        - description
        - redirect_callback
        - scopes
        - app_type
  required:
    - app
    - grants
    - data

